version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-11"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "jetty-11"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "jetty-12-ee10"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "jetty-12-ee10"
    schedule:
      interval: "daily"