version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "jetty-12-ee10"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    target-branch: "jetty-12-ee10"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    target-branch: "jetty-12-ee9"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    target-branch: "jetty-12-ee9"
    directory: "/"
    schedule:
      interval: "daily"